import numpy as np
import os

def write_cube_file(filename, density, x, y, z, nuclei, parser):
    nx, ny, nz = density.shape
    origin = np.array([x[0], y[0], z[0]])
    dx = (x[1] - x[0])
    dy = (y[1] - y[0])
    dz = (z[1] - z[0])

    file = os.path.join(os.path.dirname(parser.filename), filename)

    with open(file, 'w') as f:
        f.write("Cube file generated by script\n")
        f.write("Electron density data\n")
        f.write(f"{len(nuclei):5d} {origin[0]:12.6f} {origin[1]:12.6f} {origin[2]:12.6f}\n")
        f.write(f"{nx:5d} {dx:12.6f} 0.000000 0.000000\n")
        f.write(f"{ny:5d} 0.000000 {dy:12.6f} 0.000000\n")
        f.write(f"{nz:5d} 0.000000 0.000000 {dz:12.6f}\n")

        for atom in nuclei:
            coords_bohr = np.array(atom['coords'])
            f.write(f"{atom['atomic_number']:5d} {0.0:12.6f} {coords_bohr[0]:12.6f} {coords_bohr[1]:12.6f} {coords_bohr[2]:12.6f}\n")

        density_fixed = density.transpose(2, 1, 0)
        vals = density_fixed.flatten(order='F')
        for i in range(0, len(vals), 6):
            f.write(" ".join(f"{v:13.5e}" for v in vals[i:i+6]) + "\n")
